name: pid_control
root: ./
startup_window: ar_track
pre_window: source ~/tello_ws/devel/setup.bash
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - camera:
      layout: tiled
      panes:
        - sleep 2; roslaunch usb_cam usb_cam-test.launch 
        - sleep 5; rqt_image_view
  - ar_track:
      layout: tiled
      panes:
        - sleep 2; roslaunch ar_track_alvar pr2_indiv_no_kinect.launch
  - tello:
      layout: tiled
      panes:
        - sleep 2; roslaunch tello_driver tello_node.launch
        - sleep 5; roslaunch tello_control pid_control.launch
